apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          # resources:
          #   limits:
          #     cpu: "200m"
          #     memory: "256Mi"
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          env:
            - name: ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: endpoint-configmap
                  key: endpoint
          volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: nginx-index-file
          configMap:
            name: index-html-configmap
